# =============================================================================
# EXTENDRIX — Odoo 19 | Proyecto: motomarket | Entorno: DEV
# Contenedor: odoo19_motomarket_dev
# Generado por: sync-projects.sh
# =============================================================================

[options]

db_host = db
db_port = 5432
db_user = odoo
db_password = Kp9_mTx4_rLq8_wNz2_Vj5s
dbfilter    = ^motomarket_dev_.*$

data_dir    = /var/lib/odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

http_port   = 8069
gevent_port = 8072
http_interface = 127.0.0.1
proxy_mode  = True

workers            = 2
limit_memory_soft  = 1073741824
limit_memory_hard  = 1610612736
limit_request      = 2048
limit_time_cpu     = 120
limit_time_real    = 240
db_maxconn         = 16

log_level   = info
log_handler = :WARNING,werkzeug:CRITICAL

list_db          = True
admin_passwd = Testing@3xt3ndr1x

max_cron_threads = 1
unaccent         = True

websocket_keep_alive_timeout = 3600
websocket_rate_limit_burst   = 20
websocket_rate_limit_delay   = 0.1
