# =============================================================================
# EXTENDRIX — Odoo 19 | Proyecto: motomarket | Entorno: STA
# Contenedor: odoo19_motomarket_sta
# Generado por: sync-projects.sh
# =============================================================================

[options]

db_host = db
db_port = 5432
db_user = odoo
db_password = Kp9_mTx4_rLq8_wNz2_Vj5s
dbfilter    = ^motomarket_sta_.*$

data_dir    = /var/lib/odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/enterprise,/mnt/shared-addons,/mnt/extra-addons

http_port      = 8069
gevent_port    = 8072
http_interface =
proxy_mode     = True

workers            = 4
limit_memory_soft  = 2147483648
limit_memory_hard  = 2684354560
limit_request      = 2048
limit_time_cpu     = 60
limit_time_real    = 120
db_maxconn         = 24

log_level   = warn
log_handler = :WARNING,werkzeug:CRITICAL

list_db          = True
admin_passwd = Staging@3xt3ndr1x

max_cron_threads = 2
unaccent         = True

websocket_keep_alive_timeout = 3600
websocket_rate_limit_burst   = 10
websocket_rate_limit_delay   = 0.2
